samplesheet: /path/to/sample/table.csv
results_dir: /path/to/results/dir
reference_dir: /path/to/reference/dir
logs_dir: /path/to/logs/dir
fasta_genome: /path/to/ref/genome/file.fa.gz
mask_bed: /path/to/promoter/enhancer/anno/file.bed
chr_sizes: /path/to/chr/size/file.tsv
gtf_annotation: /path/to/reference/annotation/file.gtf.gz
genome_anno_id: hg38_gencode47
genome_code: hg38
library_config: /path/to/library/config.yml
params_set_file: config/params.csv
params_set: default